Handle static workspaces !
material-shell/material-shell pull request #413
Opened 2020-10-19 13:01 UTC by NastuzziSamy

MS override by default tweak workspace management.

Now, MS handles static workspaces coupled to cycled workspaces.

Fix: https://github.com/material-shell/material-shell/issues/378

2020-10-19 13:23 UTC, NastuzziSamy commented
Note bene: Static workspace works perfectly with auto-move extension :)

2020-10-22 16:40 UTC, PapyElGringo requested changes
Don't hesitate to test your PR before sending to prevent this kind of mistakes :)

2020-10-22 16:40 UTC, PapyElGringo commented on src/manager/msWorkspaceManager.js
> +        }
I guess there is merging error here code is unusable

2020-10-22 16:40 UTC, PapyElGringo commented on src/module/hotKeysModule.js
> +            );
this constant is overwrites ligne 169

2020-11-08 09:57 UTC, merged

2020-11-08 09:58 UTC, PapyElGringo commented
Perfect thanks you !