Rework transition to prevent reparent
material-shell/material-shell pull request #936
Opened 2023-01-02 18:13 UTC by PapyElGringo

a big change on transition reworking logic from reparent widget into specific animation container to manipulating actors directly

2023-01-04 21:01 UTC, HalfVoxel commented
Tested on `Ubuntu 22.04.1 LTS` using X11, with 3 monitors.

Everything seems to work. The only oddities I have observed are:

```
1. Click on a tab in maximize view
2. Before the transition has finished, press meta+1 to transition to another workspace.

Expected: transition to another workspace
Actual: transition to another workspace, but them immediately transition back to the original workspace.
```

```
1. Have 3 workspaces.
2. Press meta+1 to switch to the first workspace.
3. Press meta+3 to switch to the third workspace.
4. Quickly press meta+2 to switch to the second workspace before the transition has completed.
5. The second workspace will pop into view and take the place of the first midway through the transition.

I'm not quite sure how to solve this in a satisfying way, though.
```

2023-01-05 10:14 UTC, HalfVoxel requested changes

2023-01-05 10:14 UTC, HalfVoxel commented on src/utils/index.ts
> +    if (!actor || !parent || actor.get_parent() == parent) return;
Reuse the `currentParent` variable to avoid getting the parent twice (avoids a js -> c call)

2023-01-05 10:14 UTC, HalfVoxel commented on src/layout/msWorkspace/tilingLayouts/maximize.ts
> +        if (this.msWorkspace.isDisplayed()) actor.grab_key_focus();
And you are sure this will not cause other things to stop working?

2023-01-05 10:17 UTC, PapyElGringo commented on src/layout/msWorkspace/portion.ts
> +     * change order or portion by one in forward direction
index+1 in a list but in the portion context in can be vertical or horizontal should I just say "next"?

2023-01-05 10:17 UTC, HalfVoxel commented on src/layout/msWorkspace/portion.ts
> +     * change order or portion by one in forward direction
Yeah, `next` is better if there's no consistent direction.

2023-01-05 11:09 UTC, HalfVoxel approved these changes

2023-01-05 11:30 UTC, merged